[project]
name = "celery-tasks"
version = "0.1.0"
description = "공통 Celery Task 정의 및 설정"
requires-python = ">=3.13"
dependencies = [
    "celery>=5.4.0",
]

[tool.uv.sources]
celery-postgres = { workspace = true }

[tool.uv.build]
module-root = "src"

[build-system]
requires = ["uv_build>=0.5.18"]
build-backend = "uv_build"
